# Generated by Django 3.2.3 on 2021-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=3000)),
            ],
        ),
    ]
