# Generated by Django 3.2.3 on 2021-07-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210722_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
