# Generated by Django 3.2.3 on 2021-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogcomment_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
